# Sentiment Analysis of Strava Reviews Using (Aspect Mining)

In [2]:
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np
import seaborn as sns
import warnings

warnings.filterwarnings("ignore")

In [3]:
df_reviews = pd.read_csv("data/strava_reviews.csv")
display(df_reviews.head(10), df_reviews.describe(), df_reviews.shape)

,review,rating,date
0,Awsomeeee,5,2026-04-05T20:48:27-07:00
1,Paid for a subscription and it never unlocked ...,1,2026-04-05T20:25:07-07:00
2,I was immediately charged $80 for what was sup...,1,2026-04-05T18:43:31-07:00
3,The majority of the app has turned into a sche...,1,2026-04-05T12:55:19-07:00
4,Love the app but I CANNOT STAND how much it bu...,3,2026-04-04T15:41:38-07:00
5,I connected my heart rate monitor to the app. ...,1,2026-04-04T11:20:49-07:00
6,freetrailfretrail freetrailfretrail freetrailf...,1,2026-04-04T07:27:25-07:00
7,Every year Strava takes away at least one feat...,1,2026-04-04T05:51:20-07:00
8,I’ve had Strava for years and loved it. It was...,1,2026-04-03T23:10:11-07:00
9,Longtime member of Strava and lately I don’t k...,5,2026-04-02T17:13:59-07:00

           rating
count  490.000000
mean     2.965306
std      1.750495
min      1.000000
25%      1.000000
50%      3.000000
75%      5.000000
max      5.000000

(490, 3)

## Text Preprocessing

In [4]:
import spacy
import re

nlp = spacy.load("en_core_web_sm")

def clean_text(text):
    text = text.lower()
    text = re.sub(r"[^a-zA-Z\s]", "", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

df_reviews["clean_review"] = df_reviews["review"].apply(clean_text)

ModuleNotFoundError: No module named 'urllib3.packages.six.moves'